language: ruby

rvm:
  - 2.5.0

install: bundle install

before_install:
  - gem update --system
  - gem --version

before_script:
  - RAILS_ENV=production bundle exec rake db:migrate

script:
  - RAILS_ENV=production bundle exec rake